# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build distZip
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact path
        path: build/distributions
        name: sensorsfetch.zip
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: build
